### ISSUE TITLE
Kiara should expand territory to avoid long distance gathering

### ISSUE THREAD

**Issue by tuxayo** [LenaTheWolfess/Kiara#13]
Between around 45min and 50min on the south of the map, we can see long distance woodcutting outside of the territory.

replay (same as #12 )
[2022-11-06_0002.zip](https://github.com/LenaTheWolfess/Kiara/files/9945061/2022-11-06_0002.zip)

version: current main: ccaedb0b4d2ec697f8a49fa2003692158df4c841

**Comment by LenaTheWolfess** [comment]
Thank you, it should be fixed now

**Comment by tuxayo** [comment]
thanks a lot :D It's really fun to make the AIs play together and watch what they do.

**Comment by tuxayo** [comment]
It works! :)

Interesting, the replay files don't contain the AI's commands (like it does for human players) it seems. Because updating Kiara's code yielded a different replay.
It make the replay less portable as it needs the exact same AI code. But it allows to replay matches and see if the updated AI does better :)
(only in the cases where that doesn't cause changes too early in the game that butterfly effect into too different conditions later and prevents comparing the old and new AI)
